// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzsOqE_k64-qn0lwNdKWfUajf227VUIUg',
    appId: '1:234872063335:web:1ae122d5fac120c681dbc2',
    messagingSenderId: '234872063335',
    projectId: 'totem-notes',
    authDomain: 'totem-notes.firebaseapp.com',
    storageBucket: 'totem-notes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsmTVaXImUDyozyT4rZ8WVyNj-t3cacHo',
    appId: '1:234872063335:android:5f570304f3a49c0781dbc2',
    messagingSenderId: '234872063335',
    projectId: 'totem-notes',
    storageBucket: 'totem-notes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5rED4is9N17echC3U4I-TzTBE7YRu2nQ',
    appId: '1:234872063335:ios:04b931dc19a73ce681dbc2',
    messagingSenderId: '234872063335',
    projectId: 'totem-notes',
    storageBucket: 'totem-notes.appspot.com',
    iosBundleId: 'com.example.totemNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5rED4is9N17echC3U4I-TzTBE7YRu2nQ',
    appId: '1:234872063335:ios:40ae672dc40fc27281dbc2',
    messagingSenderId: '234872063335',
    projectId: 'totem-notes',
    storageBucket: 'totem-notes.appspot.com',
    iosBundleId: 'com.example.totemNotes.RunnerTests',
  );
}
